### PR TITLE
allow activesupport 6 in gemspec for Rails 6 compatibility

### PR DESCRIPTION
**Pull request by thilonel**

### CODE REVIEW

**Review by Azdaroth — APPROVED** [review]
💪 🐉 Opa!

**Comment by thilonel** [comment]
@Azdaroth hm why is there no CI here?

**Comment by Azdaroth** [comment]
@thilonel Hmm, there is no Circle config, there is only a One for Travis :/

**Comment by thilonel** [comment]
@Azdaroth Travis would be good enough as this is opensource, but I don't see that either.

**Comment by Azdaroth** [comment]
@thilonel https://travis-ci.org/BookingSync/active_merchant/

I guess pushing something one more time  here is going to trigger a build

**Comment by thilonel** [comment]
It's working, thanks!

**Comment by thilonel** [comment]
@Azdaroth could you please review again? I had to remove that gateway because the specs were failing and I couldn't figure out why.

**Review by Azdaroth — APPROVED** [review]
💪 🐉 Opa!

So Easy Pay - So Easy Removal 😂

**Pull request merged**
